language: node_js
node_js:
# 不要用 stable 坑 版本太高 gulp的时候会报错 
- 8.11.3
cache:
  directories:
  - node_modules
before_install:
- npm install hexo-cli -g
install:
- npm install

script:
- hexo clean
- hexo generate && gulp

after_script:
  - cd ./public
  - git init
  - git config user.name "mfrank2016"
  - git config user.email "337603640@qq.com"
  - git add .
  - git commit -m "auto commit by TravisCI at `date +%Y%m%d`"
   # GitHub Pages
  - git push --force --quiet "https://${GITHUB_ACCESS_TOKEN}@github.com/MFrank2016/mfrank2016.github.io.git" master:master 
